string = input('Введите строку: ')
print(f'1) {string[2]}')
print(f'2) {string[-2]}')
print(f'3) {string[:5]}')
print(f'4) {string[:-2]}')
print(f'5) {string[::2]}')
print(f'6) {string[1::2]}')
print(f'7) {string[::-1]}')
print(f'8) {string[::-2]}')
print(f'9) {len(string)}')